import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Barlow } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { StoreProvider } from 'common/redux'

import '@mantine/core/styles.css'
import './globals.css'

const barlow = Barlow({
  subsets: ['latin-ext'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={barlow.className}>
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <MantineProvider>
              <div className={'flex flex-col justify-between gap-6 min-h-screen'}>{children}</div>
            </MantineProvider>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
